# Generated from generate_labels.py

#  FOR RANK + RAG  + TRAJ SEG = 5 - REASONING MODEL
LLM_BALANCED_ACCURACY = 0.3406
REWARD_MODEL_BALANCED_ACCURACY = 0.3563
LLM_TP = 6
LLM_TN = 8
LLM_FP = 15
LLM_FN = 12
REWARD_TP = 5
REWARD_TN = 10
REWARD_FP = 13
REWARD_FN = 13
INVALID_FLAGS = [9]

VERSUS 

# RANK + RAG + NON REASONING MODEL
LLM_BALANCED_ACCURACY = 0.5500
REWARD_MODEL_BALANCED_ACCURACY = 0.5167
LLM_TP = 7
LLM_TN = 9
LLM_FP = 6
LLM_FN = 7
REWARD_TP = 7
REWARD_TN = 8
REWARD_FP = 7
REWARD_FN = 7
INVALID_FLAGS = [21]


#  ************************************************************************
# RANK + RAG + REASONING MODEL + TRAJ SEG 3
LLM_BALANCED_ACCURACY = 0.3188
REWARD_MODEL_BALANCED_ACCURACY = 0.3644
LLM_TP = 7
LLM_TN = 7
LLM_FP = 14
LLM_FN = 16
REWARD_TP = 8
REWARD_TN = 8
REWARD_FP = 13
REWARD_FN = 15
INVALID_FLAGS = [6]

VERSUS

# RANK + RAG + NON REASONING MODEL + TRAJ SEG 3
LLM_BALANCED_ACCURACY = 0.4313
REWARD_MODEL_BALANCED_ACCURACY = 0.2875
LLM_TP = 3
LLM_TN = 9
LLM_FP = 7
LLM_FN = 7
REWARD_TP = 2
REWARD_TN = 6
REWARD_FP = 10
REWARD_FN = 8
INVALID_FLAGS = [24]

# ********************************************************


# RANK + RAG + REASONING MODEL + TRAJ SEG 10
LLM_BALANCED_ACCURACY = 0.4099
REWARD_MODEL_BALANCED_ACCURACY = 0.5248
LLM_TP = 9
LLM_TN = 9
LLM_FP = 12
LLM_FN = 14
REWARD_TP = 11
REWARD_TN = 12
REWARD_FP = 9
REWARD_FN = 12
INVALID_FLAGS = [6]

VS

# RANK + RAG + NON REASONING MODEL + TRAJ SEG 10
LLM_BALANCED_ACCURACY = 0.4231
REWARD_MODEL_BALANCED_ACCURACY = 0.5000
LLM_TP = 4
LLM_TN = 7
LLM_FP = 6
LLM_FN = 9
REWARD_TP = 6
REWARD_TN = 7
REWARD_FP = 6
REWARD_FN = 7
INVALID_FLAGS = [24]
# ********************************************************


# RANK + NO RAG +  REASONING MODEL + TRAJ SEG 5
LLM_BALANCED_ACCURACY = 0.3591
REWARD_MODEL_BALANCED_ACCURACY = 0.3364
LLM_TP = 7
LLM_TN = 8
LLM_FP = 12
LLM_FN = 15
REWARD_TP = 6
REWARD_TN = 8
REWARD_FP = 12
REWARD_FN = 16
INVALID_FLAGS = [8]

VERSUS

# RANK + NO RAG + NON REASONING MODEL + TRAJ SEG 5
LLM_BALANCED_ACCURACY = 0.3833
REWARD_MODEL_BALANCED_ACCURACY = 0.4083
LLM_TP = 6
LLM_TN = 7
LLM_FP = 8
LLM_FN = 14
REWARD_TP = 7
REWARD_TN = 7
REWARD_FP = 8
REWARD_FN = 13
INVALID_FLAGS = [15]

# ********************************************************

# NO RANK + RAG +  REASONING MODEL + TRAJ SEG 5
LLM_BALANCED_ACCURACY = 0.3333
REWARD_MODEL_BALANCED_ACCURACY = 0.3333
LLM_TP = 5
LLM_TN = 7
LLM_FP = 11
LLM_FN = 13
REWARD_TP = 3
REWARD_TN = 9
REWARD_FP = 9
REWARD_FN = 15
INVALID_FLAGS = [6]

VERSUS

# NO RANK + RAG + NON REASONING MODEL + TRAJ SEG 5
LLM_BALANCED_ACCURACY = 0.4375
REWARD_MODEL_BALANCED_ACCURACY = 0.4062
LLM_TP = 6
LLM_TN = 8
LLM_FP = 8
LLM_FN = 10
REWARD_TP = 5
REWARD_TN = 8
REWARD_FP = 8
REWARD_FN = 11
INVALID_FLAGS = [18]
# ********************************************************#  
# 
# FOR RANK + RAG  + TRAJ SEG = 5 - REASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.4062
REWARD_MODEL_BALANCED_ACCURACY = 0.3101
LLM_TP = 5
LLM_TN = 13
LLM_FP = 13
LLM_FN = 11
REWARD_TP = 5
REWARD_TN = 8
REWARD_FP = 18
REWARD_FN = 11
INVALID_FLAGS = [8]

VERSUS

# FOR RANK + RAG  + TRAJ SEG = 5 - NONREASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.3932
REWARD_MODEL_BALANCED_ACCURACY = 0.2927
LLM_TP = 3
LLM_TN = 10
LLM_FP = 8
LLM_FN = 10
REWARD_TP = 4
REWARD_TN = 5
REWARD_FP = 13
REWARD_FN = 9
INVALID_FLAGS = [19]
# ********************************************************

# FOR RANK + RAG  + TRAJ SEG = 3 - REASONING MODEL, ENTROPY-BASED SAMPLING
# # FOR RANK + RAG  + TRAJ SEG = 3 - NONREASONING MODEL, ENTROPY-BASED SAMPLING


# # FOR RANK + RAG  + TRAJ SEG = 3 - NONREASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.4522
REWARD_MODEL_BALANCED_ACCURACY = 0.3051
LLM_TP = 3
LLM_TN = 9
LLM_FP = 8
LLM_FN = 5
REWARD_TP = 3
REWARD_TN = 4
REWARD_FP = 13
REWARD_FN = 5
INVALID_FLAGS = [25]

VERSUS

# FOR RANK + RAG  + TRAJ SEG = 3 - REASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.4551
LLM_TP = 5
LLM_TN = 15
LLM_FP = 11
LLM_FN = 10
REWARD_TP = 4
REWARD_TN = 9
REWARD_FP = 17
REWARD_FN = 11
INVALID_FLAGS = [9]
# ********************************************************



# FOR RANK + RAG  + TRAJ SEG = 10 - NONREASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.5357
REWARD_MODEL_BALANCED_ACCURACY = 0.3190
LLM_TP = 5
LLM_TN = 12
LLM_FP = 9
LLM_FN = 5
REWARD_TP = 4
REWARD_TN = 5
REWARD_FP = 16
REWARD_FN = 6
INVALID_FLAGS = [19]


VERSUS


# FOR RANK + RAG  + TRAJ SEG = 10 - REASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.3826
REWARD_MODEL_BALANCED_ACCURACY = 0.2739
LLM_TP = 3
LLM_TN = 13
LLM_FP = 10
LLM_FN = 12
REWARD_TP = 3
REWARD_TN = 8
REWARD_FP = 15
REWARD_FN = 12
INVALID_FLAGS = [12]
# *****************************************************


# FOR RANK + NO RAG TRAJ SEG = 5 - REASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.4328
REWARD_MODEL_BALANCED_ACCURACY = 0.2899
LLM_TP = 5
LLM_TN = 16
LLM_FP = 12
LLM_FN = 12
REWARD_TP = 5
REWARD_TN = 8
REWARD_FP = 20
REWARD_FN = 12
INVALID_FLAGS = [5]


VERSUS


# FOR RANK + NO RAG TRAJ SEG = 5 - NONREASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.6731
REWARD_MODEL_BALANCED_ACCURACY = 0.2548
LLM_TP = 4
LLM_TN = 11
LLM_FP = 2
LLM_FN = 4
REWARD_TP = 1
REWARD_TN = 5
REWARD_FP = 8
REWARD_FN = 7
INVALID_FLAGS = [29]
# *****************************************************

# FOR NO RANK + RAG TRAJ SEG = 5 - NONREASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.5783
REWARD_MODEL_BALANCED_ACCURACY = 0.3586
LLM_TP = 6
LLM_TN = 11
LLM_FP = 7
LLM_FN = 5
REWARD_TP = 3
REWARD_TN = 8
REWARD_FP = 10
REWARD_FN = 8
INVALID_FLAGS = [21]


VERSUS


# FOR NO RANK + RAG TRAJ SEG = 5 - REASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.6905
REWARD_MODEL_BALANCED_ACCURACY = 0.5079
LLM_TP = 12
LLM_TN = 10
LLM_FP = 4
LLM_FN = 6
REWARD_TP = 8
REWARD_TN = 8
REWARD_FP = 6
REWARD_FN = 10
INVALID_FLAGS = [18]
# *****************************************************


# FOR NO RANK + NO RAG TRAJ SEG = 5 - REASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.6213
REWARD_MODEL_BALANCED_ACCURACY = 0.5161
LLM_TP = 12
LLM_TN = 11
LLM_FP = 7
LLM_FN = 7
REWARD_TP = 8
REWARD_TN = 11
REWARD_FP = 7
REWARD_FN = 11
INVALID_FLAGS = [13]

# FOR NO RANK + NO RAG TRAJ SEG = 5 - REASONING MODEL, UNIFORM SAMPLING
LLM_BALANCED_ACCURACY = 0.3345
REWARD_MODEL_BALANCED_ACCURACY = 0.5821
LLM_TP = 9
LLM_TN = 5
LLM_FP = 13
LLM_FN = 14
REWARD_TP = 14
REWARD_TN = 10
REWARD_FP = 8
REWARD_FN = 9
INVALID_FLAGS = [9]
# *****************************************************


# FOR NO RANK + NO RAG TRAJ SEG = 5 - NONREASONING MODEL, UNIFORM SAMPLING
LLM_BALANCED_ACCURACY = 0.5395
REWARD_MODEL_BALANCED_ACCURACY = 0.5811
LLM_TP = 11
LLM_TN = 6
LLM_FP = 6
LLM_FN = 8
REWARD_TP = 11
REWARD_TN = 7
REWARD_FP = 5
REWARD_FN = 8
INVALID_FLAGS = [19]


# FOR NO RANK + NO RAG TRAJ SEG = 5 - NONREASONING MODEL, ENTROPY-BASED SAMPLING
LLM_BALANCED_ACCURACY = 0.5885
REWARD_MODEL_BALANCED_ACCURACY = 0.5550
LLM_TP = 12
LLM_TN = 6
LLM_FP = 5
LLM_FN = 7
REWARD_TP = 9
REWARD_TN = 7
REWARD_FP = 4
REWARD_FN = 10
INVALID_FLAGS = [20]
# *************************************************************#